chainbase-labs/manuscript-core

.github/workflows/codespell.yml
.github/workflows/main.yml
README.md

feat(codespell): add codespell and fix typo

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/document_issue.yml
.github/ISSUE_TEMPLATE/feature_request.yml
commands/init_manuscript_test.go

✨ feat(issue template): add issue template

---

.github/workflows/test.yml

🔨 fix(codecov): fix codecov

---

.github/pull_request_template.md

feat(pull request): add pull request template

---

flink/Dockerfile

🔨 chore: Updating the base docker image description

---

README.md

📝 doc: fix github version tag

---

.goreleaser.yaml

feat(version): fix version

---

install.sh

🔧 chore: Support for multi-system installation scripts

---

client/chatGPT_client.go
client/gemini_client.go
commands/chat_manuscript.go

✨ feat: Compatible with the large language model in the gaia network

---

commands/commandder.go

✨ feat: New client to show version number

---

.github/workflows/release.yml

✨feat: support versions check

---

install.sh

This PR fixes installation issues on Linux systems (specifically reported on Fedora 41) and improves the script's compatibility across different platforms.
**Key Changes:**
1. Fixed temp directory handling
- Added proper path separator for `/tmp/`
- Added `sudo` permission for temp directory creation
- Added explicit `chmod 777` for temp directory to ensure write access
2. Enhanced permission handling
- Added `sudo` for all critical file operations including:
- Directory creation
- curl download operations
- tar extraction
- File moves and cleanup
- Fixed permission issues when installing to `/usr/local/bin`
3. Improved script robustness
- Added proper quotation around variable expansions
- …

🔧 Fix: modify install script for broader compatibility

---

README.md
flink/runner/src/main/java/com/chainbase/etl/AbstractEtlSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/EtlSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/EtlSourcePlugin.java
flink/runner/src/main/java/com/chainbase/etl/PluginLoadHandler.java
flink/runner/src/main/java/com/chainbase/etl/factory/PluginFactory.java
flink/runner/src/main/java/com/chainbase/etl/flink/ETLProcessor.java
flink/runner/src/main/java/com/chainbase/etl/model/ETL.java
flink/runner/src/main/java/com/chainbase/etl/model/Sink.java
flink/runner/src/main/java/com/chainbase/etl/model/Source.java
flink/runner/src/main/java/com/chainbase/etl/model/Transform.java
flink/runner/src/main/java/com/chainbase/etl/sink/FileSystemSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/sink/PostgresSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/sink/PrintSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/sink/StarrocksSinkPlugin.java
flink/runner/src/main/java/com/chainbase/etl/source/EtlPaimonSourcePlugin.java

✨ feat: refactoring flink code logic and adding batch mode

---

gui/src/config.rs

🔧 fix: fix the issue of not finding the configuration file

---

Makefile

Adds a **_Makefile_** to streamline building both Go CLI and Rust GUI components. The Makefile implements the following:
- Adds unified build commands via `make` for `manuscript-cli` and `manuscript-gui`
- Includes proper `ldflags` for version information in golang
- Provides clean, test, help, and install targets for `make` command
- Dutiful user feedback on what is missing in builds/installs
- Sophisticated error handling and graceful exits
Addresses concerns raised in the following places:
- Issue #67 - simplifies documentation process for build / install from source
- Issue #76  - eliminates explicit `ldflags` required when building
When running `make`
When running `make all`
When running `make …

:hammer: feat: add Makefile for Unified Build System

---

flink/runner/src/main/java/com/chainbase/manuscript/ETLProcessor.java

- [v] Please open an issue before creating a PR or link to an existing issue
- [v] I have performed a self-review of my own code
- [v] I have commented my code, particularly in hard-to-understand areas
Fixed a typo: 'topoc' was changed to 'topic'.
Adjusted the SQL statement to ensure all %s placeholders were properly matched with corresponding values to prevent errors."
Fixes #86 
- [v] Bug fix

Fix: modify createKafkaSink

---

README.md

✏️ doc: new makefile supports local compilation and installation of the client

---

README.md

✏️ doc: add configuration file and data directory description

---

gui/Cargo.lock
gui/Cargo.toml
gui/src/lib.rs
gui/src/logger.rs
gui/src/main.rs
gui/src/tasks/tasks.rs

🔧 fix: fix port occupancy issue

---

cli/static/docker_compose_template.go

🔧 fix: fix network port conflicts caused by multiple jobs

---

cli/commands/commander.go
cli/commands/init_manuscript.go
cli/commands/init_manuscript_test.go

Adds support for creating manuscripts via command line arguments, allowing users to bypass the interactive prompt flow when initializing new manuscripts.
In other words, this PR adds the ability to initialize manuscripts directly through command-line arguments, providing a faster workflow for users who know their desired configuration.
Fixes #80 
```bash
manuscript-cli init
```
```bash
manuscript-cli init create <manuscript-name> --output <output-type> --protocol <database-name> --dataset <table-name>
```
- `manuscript-name`: Name/path for the new manuscript (e.g., "solana_maxi")
- `--output`: Output type (either "postgresql" or "console")
- `--protocol`: Database name from available options (e.g., …

✨ feat: add non-interactive manuscript `init` CLI command

---

README.md
cli/commands/init_manuscript.go
cli/commands/jobs_manuscript.go

Support register manuscript as IP asset on Story

---

cli/client/network_chains.go
cli/commands/init_manuscript.go
cli/static/docker_compose_template.go
flink/runner/pom.xml
flink/runner/src/main/java/com/chainbase/etl/PluginLoadHandler.java
flink/runner/src/main/java/com/chainbase/etl/flink/ETLProcessor.java
flink/runner/src/main/java/com/chainbase/manuscript/ETLProcessor.java
gui/src/prerun/prerun.rs

We're excited to announce that Manuscript now fully integrates Chainbase Platform as a core data provider, significantly expanding our data coverage, accuracy, and freshness. This upgrade delivers substantial improvements to our dataset quality and analytical capabilities. …

✨ feat: Integrate Chainbase Platform as Primary Data Source to Enhance Manuscript's Data Capabilities

---

README.md
flink/runner/src/main/java/com/chainbase/evm/ContractDiscriminator.java
flink/runner/src/main/java/com/chainbase/manuscript/ETLProcessor.java
flink/runner/src/main/java/com/chainbase/udf/math/Abs.java
flink/runner/src/main/java/com/chainbase/udf/math/Add.java
flink/runner/src/main/java/com/chainbase/udf/math/CountDistinct.java
flink/runner/src/main/java/com/chainbase/udf/math/Divide.java
flink/runner/src/main/java/com/chainbase/udf/math/Multiply.java
flink/runner/src/main/java/com/chainbase/udf/math/Negate.java
flink/runner/src/main/java/com/chainbase/udf/math/Pow.java
flink/runner/src/main/java/com/chainbase/udf/math/Subtract.java
flink/runner/src/main/java/com/chainbase/udf/math/SumStringNum.java
gui/config/default.yaml
gui/src/app.rs
gui/src/config.rs
gui/src/prerun/prerun.rs
gui/src/tasks/docker.rs
gui/src/tasks/tasks.rs
gui/src/ui.rs

- [x ] I have commented my code, particularly in hard-to-understand areas
Feat[etl]: add window dataset type source
Feat[etl]: add math udfs
Feat[gui]: support more job state

feat: flink etl and gui

---

cli/commands/init_manuscript.go
cli/commands/jobs_manuscript.go
cli/pkg/manuscript_state.go
cli/static/docker_compose_template.go

https://github.com/chainbase-labs/manuscript-core/issues/127
https://github.com/chainbase-labs/manuscript-core/issues/126
https://github.com/chainbase-labs/manuscript-core/issues/125

feat[cli]: docker compose template and job state

---

install-gui.sh

fix[gui]: install gui script

---

gui/src/tasks/docker.rs

fix[gui]:docker template

---

README.md
install-gui.sh

doc: Restore the manuscript-cli example in README

---

cli/commands/init_manuscript.go

chore: fix function name in comment

---

README.md

doc: added a link to the Apache license icon

---

cli/pkg/docker_command.go
cli/pkg/manuscript_state.go

fix some function names in comment
Fixes https://github.com/chainbase-labs/manuscript-core/issues/143

chore: fix some function names in comment

---

README.md

docs(README): edited the link to the discord badge
